#define song_watery_graves 0
#define song_celebrawl 1
#define song_adventure_start 2
#define song_final_fanfare_dot_oh_gee_gee 3
#define song_ultimate_battle 4
#define song_me_when_theres_zombies_on_my_lawn 5
#define song_crazy_dave 6
#define song_choose_your_seeds 7
#define song_moongrains 8
#define song_win_music_dot_oh_gee_gee 9
#define song_rigor_mormist 10
#define song_braniac_maniac 11
#define song_graze_the_roof_wip 12
#define song_loonboon 13
#define song_zen_garden 14
#define song_grasswalk 15
#define song_max 16