; Generated by export.py using data in metadata.json

; Music data banks
.segment "_pprg__rom__47"
	firstMusicBankPtr := *
	.include "music_0.s"
.segment "_pprg__rom__48"
	.include "music_1.s"
.segment "_pprg__rom__49"
	.include "music_2.s"

; DMC banks
.segment "_pprg__rom__50"
	firstDMCBankPtr := *
	.incbin "music_bank0.dmc"
.segment "_pprg__rom__51"
	.incbin "music_bank1.dmc"

; PCM includes

; Constants
FIRST_MUSIC_BANK = .bank(firstMusicBankPtr)
FIRST_DMC_BANK = .bank(firstDMCBankPtr)
