#define song_watery_graves 0
#define song_graze_the_roof_wip 1
#define song_test_dong_with_hihats_only 2
#define song_grasswalk 3
#define song_moongrains 4
#define song_braniac_maniac 5
#define song_win_music_dot_oh_gee_gee 6
#define song_crazy_dave 7
#define song_rigor_mormist 8
#define song_loonboon 9
#define song_celebrawl 10
#define song_max 11