; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for PVZ Deplanted music:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DELTA_COUNTER = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_pvz_deplanted_music1:=music_data_pvz_deplanted_music1

music_data_pvz_deplanted_music1:
	.byte 2
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : watery graves
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	;
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	;
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	;
	.word 145,121
; 01 : dpcm
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	;
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	;
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	;
	.word 307,256
; 02 : me when there's zombies on my lawn
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song2ch5
	;
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song2ch6
	;
	;AMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song2ch7
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song2ch8
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song2ch9
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song2ch10
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song2ch11
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song2ch12
	;
	;AMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song2ch13
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song2ch14
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song2ch15
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song2ch16
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song2ch17
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song2ch18
	;
	;AMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song2ch19
	;
	.word 215,179

.export music_data_pvz_deplanted_music1
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env14,@env12,@env13,@env0 ; 00 : blank

@instruments_exp:
	.word @env10, @env12, @env0 ; 00 : 28. organ (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch0
	.word @env10, @env12, @env0 ; 01 : 1. Piano (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch1
	.word @env10, @env12, @env0 ; 02 : 2. pizzicato (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch2
	.word @env10, @env12, @env0 ; 03 : 21. Pizzicato (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch3
	.word @env8, @env12, @env0 ; 04 : blank: epsm edition
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch4
	.word @env10, @env12, @env0 ; 05 : 5. strings (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch5
	.word @env6, @env12, @env25 ; 06 : 7. Harp (PSG)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch7
	.word @env10, @env12, @env5 ; 07 : 3. Oboe (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch8
	.word @env10, @env12, @env0 ; 08 : 27. sinewave (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch9
	.word @env10, @env12, @env0 ; 09 : 6. Attacker Bass (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch10
	.word @env10, @env12, @env0 ; 0a : 8. Acoustic Bass (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch11

@instrument_epsm_extra_patch0:
	.byte $07,$c0,$46,$1f,$10,$0c,$69,$00,$73,$1f,$00,$04,$08,$00,$62,$1f,$00,$05,$0a,$00,$20,$1f,$04,$00,$f8,$00,$1d,$1d,$16,$16,$00
@instrument_epsm_extra_patch1:
	.byte $3a,$c0,$01,$1f,$18,$04,$34,$00,$33,$1f,$00,$00,$f4,$00,$32,$1f,$04,$00,$b1,$00,$01,$1d,$0c,$00,$f7,$00,$1b,$25,$2c,$11,$00
@instrument_epsm_extra_patch2:
	.byte $13,$c0,$72,$1f,$1b,$0a,$78,$00,$31,$1f,$1f,$06,$06,$00,$24,$1f,$15,$10,$78,$00,$11,$1f,$10,$0e,$38,$00,$25,$22,$15,$10,$00
@instrument_epsm_extra_patch3:
	.byte $13,$c0,$72,$1f,$16,$18,$48,$00,$31,$1f,$1f,$0d,$06,$00,$24,$1f,$15,$10,$48,$00,$11,$1f,$1f,$10,$09,$00,$10,$22,$17,$0e,$00
@instrument_epsm_extra_patch4:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch5:
	.byte $24,$c0,$31,$13,$00,$04,$13,$00,$21,$10,$01,$04,$16,$00,$73,$14,$00,$04,$13,$00,$61,$0e,$00,$04,$26,$00,$21,$1c,$1d,$1b,$00
@instrument_epsm_extra_patch7:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch8:
	.byte $2b,$c0,$21,$1f,$00,$00,$02,$00,$22,$1f,$00,$00,$02,$00,$00,$1f,$00,$00,$00,$00,$42,$10,$00,$00,$07,$00,$1e,$27,$7f,$15,$00
@instrument_epsm_extra_patch9:
	.byte $3e,$c0,$02,$1f,$00,$09,$0b,$00,$01,$1f,$00,$02,$0b,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$7f,$0e,$7f,$7f,$00
@instrument_epsm_extra_patch10:
	.byte $32,$c0,$30,$1f,$15,$02,$62,$00,$75,$1f,$1f,$00,$06,$00,$22,$1f,$0e,$00,$48,$00,$61,$1f,$1f,$00,$09,$00,$09,$2e,$19,$16,$00
@instrument_epsm_extra_patch11:
	.byte $1c,$c0,$00,$1f,$0f,$00,$27,$00,$01,$1f,$00,$00,$09,$00,$03,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$0a,$00,$15,$13,$37,$13,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c5,$00,$01
@env2:
	.byte $c2,$c5,$00,$01
@env3:
	.byte $00,$c9,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$09
@env4:
	.byte $c6,$7f,$00,$00
@env5:
	.byte $00,$c0,$07,$c0,$c1,$c1,$c2,$c2,$c1,$c1,$c0,$bf,$bf,$be,$be,$bf,$bf,$00,$03
@env6:
	.byte $1b,$cf,$cd,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$02,$c6,$02,$c5,$03,$c4,$03,$c3,$04,$c2,$c2,$c2,$00,$18,$c2,$02,$c1,$05,$c0,$08,$c0,$00,$21
@env7:
	.byte $b8,$be,$00,$01
@env8:
	.byte $04,$cf,$00,$01,$ca,$c5,$c0,$00,$06
@env9:
	.byte $00,$cf,$c6,$c2,$c0,$00,$04
@env10:
	.byte $00,$cf,$7f,$00,$02
@env11:
	.byte $ca,$7f,$00,$00
@env12:
	.byte $c0,$7f,$00,$01
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $04,$cf,$00,$01,$c0,$00,$04
@env15:
	.byte $c1,$7f,$00,$00
@env16:
	.byte $c0,$c5,$00,$01
@env17:
	.byte $00,$cf,$c8,$c5,$c4,$c3,$c2,$c1,$c0,$00,$08
@env18:
	.byte $00,$cf,$cc,$c9,$c6,$c5,$c3,$c1,$c0,$00,$08
@env19:
	.byte $c8,$7f,$00,$00
@env20:
	.byte $c9,$d1,$00,$01
@env21:
	.byte $00,$cf,$ca,$c7,$c4,$c3,$c2,$c1,$c0,$00,$08
@env22:
	.byte $00,$c4,$c3,$c2,$c1,$c1,$c0,$00,$06
@env23:
	.byte $00,$cb,$c6,$c3,$c2,$c1,$c0,$00,$06
@env24:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@env25:
	.byte $00,$bf,$c0,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$7e,$0f,$40,$08 ; 00 B3 - industrial bass (Pitch:15)
	.byte $1f+.lobyte(FAMISTUDIO_DPCM_PTR),$11,$0f,$40,$07 ; 01 bongos - C5 (Pitch:15)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$17,$0f,$40,$07 ; 02 bongos - D5 (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$1b,$0f,$40,$07 ; 03 bongos - Db5 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3d,$0f,$40,$07 ; 04 bongos - E5 (Pitch:15)
	.byte $16+.lobyte(FAMISTUDIO_DPCM_PTR),$23,$0f,$40,$07 ; 05 bongos - Eb5 (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$40,$08 ; 06 C3 - smash bass drum (Pitch:15)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$08,$0f,$40,$08 ; 07 C6 - plink (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$2e,$0f,$40,$08 ; 08 D4 - metal light (Pitch:15)
	.byte $6c+.lobyte(FAMISTUDIO_DPCM_PTR),$0c,$0f,$40,$08 ; 09 Db6 - bonk3 (Pitch:15)
	.byte $2b+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0f,$40,$07 ; 0a dice (Pitch:15)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$07 ; 0b dice2 (Pitch:15)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$0f,$40,$07 ; 0c E4 - metal loud (Pitch:15)
	.byte $71+.lobyte(FAMISTUDIO_DPCM_PTR),$16,$0f,$40,$08 ; 0d E6 - bonk4 (Pitch:15)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$0e,$40,$08 ; 0e Eb6 - bonk (Pitch:14)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$0f,$40,$08 ; 0f Eb6 - bonk (Pitch:15)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$04 ; 10 evillaugh0 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 11 evillaugh1 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 12 evillaugh2 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 13 evillaugh3 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 14 evillaugh4 (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$9e,$0f,$40,$08 ; 15 F4 - oil drum snare (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$3e,$02 ; 16 finalfanfare0 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$38,$02 ; 17 finalfanfare1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$58,$03 ; 18 finalfanfare2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$03 ; 19 finalfanfare3 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e9,$0f,$4c,$04 ; 1a finalfanfare4 (Pitch:15)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$50,$0f,$40,$01 ; 1b industrial snare (Pitch:15)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$3b,$0f,$40,$09 ; 1c laser dabs (Pitch:15)
	.byte $19+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$09 ; 1d scratch standard (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$0f,$40,$09 ; 1e snarish drum (Pitch:15)
	.byte $42+.lobyte(FAMISTUDIO_DPCM_PTR),$88,$0d,$40,$07 ; 1f sunflower (Pitch:13)
	.byte $3f+.lobyte(FAMISTUDIO_DPCM_PTR),$0a,$0f,$40,$07 ; 20 tennis (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 21 winmusic0 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 22 winmusic1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 23 winmusic2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$97,$0f,$40,$01 ; 24 winmusic3 (Pitch:15)

@song0ch0:
	.byte $46, $02
@song0ch0loop:
@song0ref4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $78, $51, $fe, $40, $4e, $ff, $80
@song0ref25:
	.byte $2c, $8d, $78, $51, $fe, $50, $2a, $89, $78, $51, $fe, $10, $27, $a1, $7f, $4e, $00, $00, $bd, $78, $51, $fe, $40, $4e
	.byte $ff, $2c, $8d, $78, $51, $fe, $50, $2a, $89, $78, $51, $fe, $10, $27, $a1, $7f, $4e, $00, $00, $bd, $78, $51, $fe, $40
	.byte $4e, $ff
	.byte $41, $10
	.word @song0ref25
	.byte $bf, $ff, $ff, $ff, $ff, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $41, $0e
	.word @song0ref4
	.byte $74, $51, $fe, $10, $4e, $01, $4f, $03, $80
@song0ref99:
	.byte $38, $8d, $74, $51, $fe, $10, $36, $89, $74, $51, $ff, $00, $33, $a1, $7f, $4e, $00, $00, $bd, $74, $51, $fe, $10, $4e
	.byte $01, $4f, $03, $38, $8d, $74, $51, $fe, $10, $36, $89, $74, $51, $ff, $00, $33, $a1, $7f, $4e, $00, $00, $bd, $74, $51
	.byte $fe, $10, $4e, $01, $4f, $03
	.byte $41, $10
	.word @song0ref99
	.byte $bf, $ff, $ff, $ff, $ff, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $ff, $80
@song0ref168:
	.byte $27, $81, $00, $81, $2c, $81, $00, $89, $27, $81, $00, $81, $28, $81, $00, $81, $28, $00, $83, $48, $01, $28, $00, $8b
	.byte $25, $81, $00, $81, $28, $81, $00, $89, $25, $81, $00, $81, $27, $81, $00, $81, $27, $00, $83, $48, $01, $27, $00, $8b
	.byte $41, $26
	.word @song0ref168
	.byte $33, $81, $00, $81, $32, $81, $00, $81, $36, $81, $00, $81
	.byte $41, $2c
	.word @song0ref168
	.byte $41, $16
	.word @song0ref168
	.byte $27, $81, $00, $81, $27, $00, $83, $2a, $81, $00, $81, $2a, $00, $83, $2c, $81, $33, $81, $00, $81, $2c, $81, $2e, $81
	.byte $2a, $81, $00, $81, $27, $81, $7e
@song0ref268:
	.byte $2c, $81, $45, $81, $2c, $81, $2c, $81, $33, $81, $2c, $81, $45, $81, $2c, $81, $45, $81, $2b, $81, $45, $81, $2c, $81
	.byte $33, $81, $2c, $81, $45, $81, $2c, $81, $2b, $81, $45, $81, $2b, $81, $2b, $81, $33, $81, $2b, $81, $45, $81, $2b, $81
	.byte $45, $81, $2b, $81, $45, $81, $2b, $81, $45, $8d, $2a, $81, $45, $81, $2a, $81, $2a, $81, $33, $81, $2a, $81, $45, $81
	.byte $2a, $81, $45, $81, $2a, $81, $45, $81, $2a, $81, $33, $81, $38, $81, $33, $81, $2a, $81
	.byte $41, $0d
	.word @song0ref268
	.byte $85
@song0ref362:
	.byte $2c, $81, $33, $81, $38, $81, $45
@song0ref369:
	.byte $81, $38, $00, $83, $48, $01, $38, $00, $83, $28, $81, $2f, $81, $34, $81, $45, $81, $34, $00, $83, $48, $01, $34, $00
	.byte $83, $27, $81, $2e, $81, $33, $81, $45, $81, $33, $00, $83, $48, $01, $33, $00, $83
	.byte $41, $0e
	.word @song0ref362
	.byte $29, $81, $2c, $81, $31, $81, $45, $81, $31, $00, $83, $48, $01, $31, $00, $83, $28, $81, $2c, $81, $2f, $81, $45, $81
	.byte $2f, $00, $83, $48, $01, $2f, $00, $83, $25, $81, $28, $81, $2c, $81, $45, $81, $2c, $00, $83, $48, $01, $2c, $00, $c3
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $bf, $2d, $81, $34, $81, $39, $81, $00, $81, $39, $00, $83, $48, $01, $39, $00, $83, $2c
	.byte $81, $33, $81, $38, $81, $00
	.byte $41, $0d
	.word @song0ref369
	.byte $2f, $81, $2a, $81, $31, $81, $36, $81, $38, $81, $00, $81, $38, $00, $83, $48, $01, $38, $00, $8f
@song0ref514:
	.byte $31, $81, $34, $81, $38, $81, $3b, $81, $38, $81, $00, $81, $48, $01, $38, $00, $31, $81, $00, $81, $31, $00, $83, $48
	.byte $02, $31, $00, $83, $48, $01, $31, $00, $87
	.byte $41, $0c
	.word @song0ref514
	.byte $38, $00, $a3
@song0ref553:
	.byte $33, $85, $2f, $85, $2c, $85, $00, $81, $31, $9d, $00, $89, $31, $81, $2f, $81, $31, $81, $33, $81, $00, $81, $2f, $81
	.byte $00, $81, $2e, $81, $00, $81, $2c, $81, $00, $81, $27, $81, $2f, $81, $31, $81, $00, $85, $33, $85, $00, $81, $33, $81
	.byte $00, $81, $31, $85, $00, $89, $36, $85, $31, $9d, $2f, $91, $2c, $81, $2f, $81, $2c, $81, $2f, $81, $31, $81
	.byte $41, $3b
	.word @song0ref553
	.byte $8d, $00, $95, $42
	.word @song0ch2loop
@song0ch16:
@song0ch7:
@song0ch3:
@song0ch3loop:
	.byte $41, $0e
	.word @song0ref4
	.byte $ff, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $ff, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0e
	.word @song0ref4
	.byte $ff, $ff, $ff, $ff, $bf
@song0ref659:
	.byte $05, $81, $03, $85, $06, $81, $02, $85, $05, $81, $05, $85, $03, $81, $04, $81, $06, $81, $02, $85, $05, $85
	.byte $41, $13
	.word @song0ref659
	.byte $81, $04, $81, $02, $81, $04, $81
	.byte $41, $16
	.word @song0ref659
	.byte $41, $13
	.word @song0ref659
	.byte $81, $04, $81, $02, $81, $04, $81
	.byte $41, $16
	.word @song0ref659
	.byte $41, $13
	.word @song0ref659
	.byte $81, $04, $81, $02, $81, $04, $81
	.byte $41, $16
	.word @song0ref659
	.byte $05, $81, $03, $85, $06, $81, $02, $85, $05, $81, $05, $81, $52, $80, $00, $9d, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $00, $bd, $7d, $8c
@song0ref744:
	.byte $2c, $85, $33, $85, $38, $85, $33, $85, $7a, $2c, $85, $33, $85, $38, $85, $33, $85, $00, $bd, $7d
	.byte $41, $10
	.word @song0ref744
	.byte $2c, $85, $00, $b5, $7d, $31, $85, $34, $85, $38, $85, $34, $85, $7a, $2c, $85, $33, $85, $38, $85, $33, $85, $7d
	.byte $41, $10
	.word @song0ref744
	.byte $7d, $31, $85, $34, $85, $38, $85, $34, $85, $7a, $2c, $85, $00, $95, $7d
	.byte $41, $10
	.word @song0ref744
	.byte $7d
@song0ref812:
	.byte $31, $85, $34, $85, $38, $85, $34, $85, $2c, $85, $33, $85, $38, $85, $33, $85
	.byte $41, $10
	.word @song0ref744
	.byte $7d
@song0ref832:
	.byte $2c, $85, $34, $85, $2e, $85, $36, $85, $2f, $85, $38, $85, $31, $85, $3a, $85
@song0ref848:
	.byte $2c, $85, $33, $8d, $33, $85, $2c, $85, $33, $95, $2b, $85, $33, $8d, $33, $85, $2b, $85, $33, $95
@song0ref868:
	.byte $2a, $85, $33, $8d, $33, $85, $2a, $85, $33, $95, $2c, $85, $7a, $33, $85, $79, $38, $85, $7a, $33, $85, $7d, $2c, $85
	.byte $7a, $33, $85, $79, $38, $85, $7a, $33, $85, $7d
@song0ref902:
	.byte $28, $85, $2f, $8d, $2f, $85, $2e, $85, $34, $81, $33, $89, $33, $81, $2e, $81, $2f, $81, $2e, $81, $2f, $81, $31, $81
	.byte $33, $81, $2c, $81, $2f, $81, $33, $81, $38, $85, $7a, $38, $85, $78, $38, $85, $76, $38, $85, $7d
@song0ref946:
	.byte $28, $85, $2f, $8d, $2f, $85, $25, $85, $2f, $8d, $2f, $81, $25, $81, $27, $81, $26, $81, $27, $81, $29, $81, $2b, $81
	.byte $27, $81, $29, $81, $2e, $81, $33, $85, $7a, $33, $85, $78, $33, $85, $76, $33, $85, $7d
	.byte $41, $65
	.word @song0ref848
	.byte $85, $2e, $8d, $2e, $85, $27, $85, $2e, $95
@song0ref1000:
	.byte $97, $2c, $81, $2c, $81, $2c, $85, $33, $85, $38, $85, $33, $b5, $2c, $85, $27, $85
	.byte $41, $11
	.word @song0ref1000
	.byte $41, $0c
	.word @song0ref1000
	.byte $c5, $00, $95, $2c, $81, $2c, $81
@song0ref1030:
	.byte $2c, $85, $33, $85, $38, $85, $33, $a9, $2a, $81, $2c, $81, $2e, $81, $2f, $8d, $00, $a1
@song0ref1048:
	.byte $2a, $81, $2c, $81, $2e, $81, $2f, $81, $31, $81, $33, $81, $34, $81, $00, $fd, $ff, $ff, $ff, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $4e, $01, $83, $00, $bd, $7a, $8c
@song0ref1078:
	.byte $2c, $85
@song0ref1080:
	.byte $33, $85, $38, $85, $33, $85, $2c, $85, $33, $85, $38, $85, $33, $81, $4e, $01, $83, $00, $bd
	.byte $41, $10
	.word @song0ref1078
	.byte $83, $2c, $85, $00, $b5
	.byte $41, $0f
	.word @song0ref812
	.byte $81, $83
	.byte $41, $0f
	.word @song0ref1078
	.byte $85, $31, $85, $34, $85, $38, $85, $34, $85, $2c, $85, $00, $91, $83
	.byte $41, $0f
	.word @song0ref1078
	.byte $85
	.byte $41, $0f
	.word @song0ref812
	.byte $81, $83
	.byte $41, $0f
	.word @song0ref1078
	.byte $85
	.byte $41, $0f
	.word @song0ref832
	.byte $81, $83
	.byte $41, $13
	.word @song0ref848
	.byte $91, $83
	.byte $41, $0c
	.word @song0ref868
	.byte $41, $0e
	.word @song0ref1080
	.byte $83
	.byte $41, $22
	.word @song0ref902
	.byte $38, $85, $38, $85, $38, $81, $83
	.byte $41, $20
	.word @song0ref946
	.byte $33, $85, $33, $85, $33, $81, $83
	.byte $41, $13
	.word @song0ref848
	.byte $91, $83
	.byte $41, $0c
	.word @song0ref868
	.byte $41, $0e
	.word @song0ref1080
	.byte $83
	.byte $41, $22
	.word @song0ref902
	.byte $38, $85, $38, $85, $38, $81, $83
	.byte $41, $0f
	.word @song0ref946
	.byte $85, $2e, $8d, $2e, $85, $27, $85, $2e, $91, $83, $00, $9d
@song0ref1216:
	.byte $2c, $85, $33, $85, $38, $85, $33, $b5, $2c, $85, $27, $81, $a3
	.byte $41, $0d
	.word @song0ref1216
	.byte $2c, $85, $33, $85, $38, $85, $33, $c1, $00, $a1
	.byte $41, $0f
	.word @song0ref1030
	.byte $89, $a7
	.byte $41, $0c
	.word @song0ref1048
	.byte $00, $fd, $ff, $ff, $ff, $42
	.word @song0ch6loop
@song0ch8:
@song0ch8loop:
	.byte $7c, $82
@song0ref1261:
	.byte $2c, $8d, $37, $8d, $36, $95, $78, $35, $9d, $75, $35, $9d, $73, $35, $85, $7c
	.byte $41, $0c
	.word @song0ref1261
	.byte $7c
	.byte $41, $0c
	.word @song0ref1261
	.byte $7c
@song0ref1285:
	.byte $00, $85, $8e
@song0ref1288:
	.byte $38, $81, $5c, $85, $33, $81, $5c, $85, $36, $81, $5c, $85, $34, $81, $5c, $85, $31, $81, $5c, $89, $34, $81, $5c, $85
	.byte $36, $81, $5c, $85, $33, $81, $5c, $89, $82, $32, $8d
	.byte $41, $21
	.word @song0ref1285
	.byte $85, $2f, $81, $5c, $85, $2c, $81, $5c, $81, $87
	.byte $41, $13
	.word @song0ref1288
	.byte $81, $34, $8d, $36, $8d, $38, $8d, $3a, $8d, $82
@song0ref1349:
	.byte $33, $a5, $3a, $85, $38, $85, $34, $85, $33, $a5, $33, $85, $32, $85, $36, $85, $83, $33, $81, $34, $81, $36, $81, $38
	.byte $81, $3a, $81, $3b, $81, $3d, $81, $3e, $81, $3f, $81, $3b, $81, $38, $81, $33, $81, $31, $81, $2f, $81, $2c, $81, $33
	.byte $8d, $31, $89, $2c, $a1, $00, $85, $28, $85, $2a, $81, $2c, $85, $2b, $89, $2b, $85, $2c, $85, $2e, $85, $2f, $85, $2e
	.byte $85, $2f, $81, $33, $85, $2c, $a1, $87, $2c, $85, $2c, $81, $2e, $85, $2f, $85, $31, $85, $33, $85, $34, $81, $31, $81
	.byte $2f, $81, $2e, $a5, $33, $85, $32, $85, $36, $85
	.byte $41, $62
	.word @song0ref1349
	.byte $33, $99, $80, $2b, $9d, $5c, $81
@song0ref1465:
	.byte $20, $81, $5c, $89, $25
@song0ref1470:
	.byte $85, $5c, $81, $20, $81, $5c, $81, $20, $81, $27, $81, $27, $81, $20, $81, $5c, $89, $2c, $81, $5c, $99, $20, $81, $5c
	.byte $99, $82, $38, $85, $80, $20, $81, $5c, $81, $2a
	.byte $41, $14
	.word @song0ref1470
	.byte $89, $2c, $81, $5c, $89, $2c, $81, $5c, $89, $2c, $81, $5c, $89
	.byte $41, $25
	.word @song0ref1465
	.byte $41, $11
	.word @song0ref1470
	.byte $23, $81, $5c, $81, $19, $81, $5c, $81, $19, $81, $5c, $81, $25, $81, $20, $81, $5c, $9d, $20, $81, $5c, $81, $19, $81
	.byte $5c, $81, $20, $81, $5c, $81, $2a, $81, $2a, $81, $5c, $9d
@song0ref1562:
	.byte $82, $3f, $85, $3b, $85, $38, $89, $3d, $a1, $80, $1b, $81, $5c, $89, $25, $81, $5c, $85, $20, $85, $20, $81, $23, $81
	.byte $25, $81, $27, $81, $25, $81, $23, $81, $20, $81, $19, $81, $5c, $81, $23, $81, $5c, $81, $19, $81, $20, $81, $5c, $81
	.byte $1e, $91, $1c, $8d, $1b, $85, $82, $3a, $85, $36, $85, $80, $20, $91, $5c, $81, $1e, $8d
	.byte $41, $3e
	.word @song0ref1562
	.byte $42
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
	.byte $7c, $00, $85, $82
@song0ref1639:
	.byte $38, $8d, $33, $8d, $35, $9d, $78, $35, $9d, $73, $35, $95, $7c, $00, $85
	.byte $41, $0c
	.word @song0ref1639
	.byte $38, $8d, $33, $8d, $35, $9d, $78, $35, $9d, $73, $35, $95, $7c, $00, $e5, $33, $8d, $36, $85, $87, $20, $8d, $22, $81
	.byte $23, $81, $25, $a5, $25, $89, $27, $89, $23, $89, $20, $89, $1b, $85, $00, $85, $20, $8d, $22, $81, $23, $81, $25, $9d
	.byte $79, $8a, $2f, $8d, $31, $8d, $34, $8d, $31, $8d, $00, $fd, $ff, $ff, $ff, $7c, $80, $2a, $81, $5c, $81, $20, $81, $5c
	.byte $81, $23, $81, $20, $81, $5c, $81, $23, $81, $5c, $81, $20, $81, $23, $81, $5c, $91, $27, $81, $5c, $81, $1f, $81, $5c
	.byte $81, $22, $81, $28, $81, $5c, $81, $1f, $91, $5c, $8d, $1b, $81, $5c, $89, $22, $81, $5c, $85, $22, $81, $5c, $85, $22
	.byte $81, $5c, $91, $1d, $81, $5c, $81, $25, $81, $5c, $81, $1d, $81, $23, $81, $5c, $81, $1d, $91, $5c, $8d, $1c, $81, $5c
	.byte $81, $19, $81, $5c, $81, $20, $81, $23, $81, $5c, $81, $1b, $85, $5c, $81, $22, $81, $5c, $81, $1f, $85, $25, $81, $5c
	.byte $81, $1b, $85, $5c, $85, $1b, $81, $5c, $85, $19, $91, $5c, $8d, $27, $81, $5c, $89, $20, $81, $5c, $85, $20, $91, $5c
	.byte $8d, $22, $81, $5c, $89, $22, $85, $5c, $81, $22, $9d, $5c, $81
@song0ref1862:
	.byte $23, $81, $5c, $89, $22
@song0ref1867:
	.byte $85, $5c, $81, $24, $81, $5c, $8d, $24, $81, $5c, $89, $28, $81, $5c, $99, $24, $81, $5c, $99, $1c, $81, $5c, $89, $25
	.byte $41, $0f
	.word @song0ref1867
	.byte $20, $81, $5c, $99
	.byte $41, $1d
	.word @song0ref1862
	.byte $85, $5c, $81, $24, $81, $5c, $8d, $24, $81, $5c, $89, $20, $81, $5c, $89, $1c, $81, $5c, $85, $23, $81, $5c, $81, $00
	.byte $99, $23, $81, $5c, $89, $23, $81, $5c, $85, $1e, $81, $5c, $9d
@song0ref1938:
	.byte $23, $81, $5c, $89, $23, $81, $5c, $85, $1e, $91, $1c, $81, $5c, $89, $25, $81, $5c, $89, $22, $81, $5c, $85, $23, $85
	.byte $5c, $99, $87, $20, $81, $5c, $85, $23, $81, $5c, $81, $22, $a1, $1e, $95, $23, $91, $5c, $81, $22, $8d
	.byte $41, $2d
	.word @song0ref1938
	.byte $42
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $ff, $bf, $76, $51, $02, $90, $8a, $2c, $8d, $2c, $8d, $2c, $8d, $2c, $8d, $00, $85, $7a, $90
@song0ref2009:
	.byte $27, $81, $5c, $81, $2c, $81, $5c, $81, $00, $85, $27, $81, $5c, $81, $28, $81, $5c, $81, $76, $28, $81, $5c, $81, $74
	.byte $28, $81, $5c, $81, $00, $85, $7a, $25, $81, $5c, $81, $28, $81, $5c, $81, $00, $85, $25, $81, $5c, $81, $27, $81, $5c
	.byte $81, $76, $27, $81, $5c, $81, $74, $27, $81, $5c, $81, $00, $85, $7a
	.byte $41, $2e
	.word @song0ref2009
	.byte $33, $81, $5c, $81, $32, $81, $5c, $81, $00, $85
	.byte $41, $38
	.word @song0ref2009
	.byte $7a
	.byte $41, $16
	.word @song0ref2009
	.byte $28, $74, $81, $5c, $81, $00, $85, $7a, $27, $81, $5c, $81, $76, $27, $81, $5c, $81, $7a, $2a, $81, $5c, $81, $76, $2a
	.byte $81, $5c, $81, $7a, $2c, $81, $33, $81, $5c, $81, $2c, $81, $2e, $81, $2a, $81, $00, $fd, $ff, $ff, $ff, $7c, $80, $23
@song0ref2139:
	.byte $81, $5c, $89, $27, $81, $5c, $85, $27, $81, $5c, $85, $27, $81, $5c, $91, $22, $81, $5c, $89, $27, $81, $5c, $85, $22
	.byte $91, $5c, $8d, $1e
	.byte $41, $0f
	.word @song0ref2139
	.byte $20, $81, $5c, $89, $20, $81, $5c, $85, $20, $91, $5c, $8d, $20, $81, $5c, $89, $1c, $81, $5c, $85, $1f, $85, $5c, $89
	.byte $23, $81, $5c, $89, $20, $85, $5c, $85, $22, $81, $5c, $85, $1d, $91, $5c, $8d, $23, $81, $5c, $89, $23, $81, $5c, $85
	.byte $23, $91, $5c, $8d, $27, $81, $5c, $89, $29, $85, $5c, $81, $27, $9d, $5c, $81
@song0ref2234:
	.byte $27, $81, $5c, $89, $82, $36, $89, $80
@song0ref2242:
	.byte $27, $81, $5c, $8d, $27, $81, $5c, $89, $25, $81, $5c, $99, $27, $81, $5c, $99, $20, $81, $5c, $89, $22, $85, $5c, $81
	.byte $41, $0c
	.word @song0ref2242
	.byte $24, $81, $5c, $99
	.byte $41, $1e
	.word @song0ref2234
	.byte $27, $81, $5c, $8d, $27, $81, $5c, $89, $1c, $81, $5c, $89, $20, $81, $5c, $89, $00, $9d, $86, $27, $99, $80, $22, $81
	.byte $86, $25, $9d, $80
@song0ref2304:
	.byte $20, $81, $5c, $89, $20, $81, $5c, $85, $22, $a1, $22, $81, $5c, $81, $82, $3d, $85, $80, $1e, $81, $5c, $a9, $87, $19
	.byte $81, $5c, $b1, $22, $8d, $22, $85, $5c, $a5
	.byte $41, $1f
	.word @song0ref2304
	.byte $42
	.word @song0ch10loop
@song0ch11:
@song0ch11loop:
	.byte $ff, $bf, $76, $51, $02, $90, $8a, $33, $8d, $33, $8d, $33, $8d, $33, $8d, $7c, $86
@song0ref2361:
	.byte $14, $85, $1b, $8d, $14, $85, $15, $9d, $19, $85, $1c, $8d, $19, $85, $14, $9d
	.byte $41, $0f
	.word @song0ref2361
	.byte $85, $1b, $85, $1a, $85, $1e, $85
	.byte $41, $10
	.word @song0ref2361
	.byte $14, $85, $1b, $85, $20, $85, $14, $85, $15, $85, $1c, $85, $00, $8d, $10, $85, $17, $85, $12, $85, $19, $85, $14, $85
	.byte $1b, $85, $19, $85, $16, $85
@song0ref2420:
	.byte $14, $8d, $1b, $85, $1c, $85, $1b, $8d, $17, $8d, $13, $9d, $1b, $9d, $12, $8d, $1b, $85, $1c, $85, $1b, $8d, $20, $8d
	.byte $19, $9d, $14, $9d, $19, $8d, $1c, $85, $17, $85, $16, $8d, $13, $8d, $14, $9d, $19, $95, $1c, $81, $1e, $81, $20, $8d
	.byte $1c, $8d, $1b, $8d, $19, $8d, $1b, $8d, $16, $8d, $1b, $9d
	.byte $41, $3c
	.word @song0ref2420
@song0ref2483:
	.byte $82, $38, $85, $80, $20, $81, $5c, $81, $2a, $85, $5c, $81, $82, $33, $99, $86, $20, $81, $27, $81, $27, $85, $28, $81
	.byte $25, $81, $80, $2c, $81, $86, $23, $81, $27, $81, $00, $81, $80, $2c, $81, $5c, $89, $2c, $81, $5c, $89, $23, $81, $5c
	.byte $89, $82, $3a, $85, $36, $81, $33, $95, $84, $20, $81, $27, $81, $2a, $81, $27, $85, $25, $81, $23, $85, $25, $81, $27
	.byte $85, $80, $27, $81, $5c, $99
	.byte $41, $37
	.word @song0ref2483
	.byte $81, $00, $b9, $9b, $80, $25, $81, $5c, $9d
@song0ref2573:
	.byte $19, $81, $5c, $89, $19, $81, $5c, $a9, $1e, $81, $5c, $89, $82, $3d, $81, $3f, $85, $3b, $85, $3a, $85, $38, $85, $33
	.byte $81, $3b, $81, $3d, $81, $87, $3f, $89, $3f, $85, $3d, $91, $40, $4e, $85, $3d, $85, $80, $25, $85, $25, $85, $5c, $85
	.byte $82, $3b, $91, $38, $81, $3b, $81, $38, $81, $3b, $81, $3d, $81, $80
	.byte $41, $2e
	.word @song0ref2573
	.byte $a5, $42
	.word @song0ch11loop
@song0ch12:
@song0ch12loop:
	.byte $ff, $bf, $76, $51, $02, $90, $8a, $2f, $8d, $2f, $8d, $2f, $8d, $2f, $8d, $00, $c5, $7c, $8e, $34, $81, $5c, $85, $36
	.byte $81, $5c, $85, $33, $81, $5c, $85, $2f, $81, $5c, $85, $2c, $81, $5c, $81, $87, $00, $f5, $87, $8a, $2c, $89, $5c, $81
	.byte $2e, $81, $2f, $81, $31, $81, $5c, $a1, $31, $89, $33, $89, $2f, $89, $2c, $89, $27, $85, $5c, $85, $2c, $89, $5c, $81
	.byte $2e, $81, $2f, $81, $31, $81, $5c, $99, $79, $38, $8d, $3a, $8d, $3b, $8d, $3a, $8d, $00, $fd, $ff, $ff, $ff, $7c, $80
	.byte $27, $81, $5c, $89, $2a, $81, $5c, $85, $2a, $81, $5c, $85, $2a, $81, $5c, $91, $00, $99, $27, $91, $5c, $8d, $22, $81
	.byte $5c, $b9, $27, $81, $5c, $89, $25, $81, $5c, $a9, $23, $81, $5c, $95, $22, $85, $5c, $99, $23, $85, $5c, $91, $20, $91
	.byte $5c, $8d, $1c, $81, $5c, $89, $1c, $81, $5c, $85, $1c, $91, $5c, $8d, $1f, $81, $5c, $89, $1f, $85, $5c, $81, $1f, $9d
	.byte $5c, $81, $86
@song0ref2814:
	.byte $1c, $85, $17, $85, $1e, $85, $19, $81, $20, $91, $14, $8d, $15, $85, $1c, $95, $14, $85, $1b, $95
	.byte $41, $14
	.word @song0ref2814
	.byte $41, $14
	.word @song0ref2814
	.byte $41, $0c
	.word @song0ref2814
	.byte $19, $8d, $20, $89, $19, $a1, $84, $19, $81, $78, $19, $89, $7c, $20, $81, $78, $20, $85, $7c, $1e, $81, $78, $1e, $8d
	.byte $7c, $8f
@song0ref2869:
	.byte $19, $85, $19, $85, $20, $89, $1e, $89, $1e, $85, $25, $85, $1c, $85, $1b, $85, $1e, $85, $22, $85, $1e, $85, $20, $85
	.byte $27, $95
	.byte $41, $10
	.word @song0ref2869
	.byte $1b, $85, $25, $85, $22, $81, $20, $91, $1e, $8d
@song0ref2908:
	.byte $19, $80, $25, $28, $81, $84, $19, $80, $25, $2f, $81, $84, $20, $81, $80, $2f, $81, $5c, $00, $84, $1e, $80, $28, $5c
	.byte $81
@song0ref2933:
	.byte $2e, $81, $84, $1e, $81, $80, $2e, $81, $84, $25, $81, $80, $2e, $81, $84, $1c, $85, $1b, $80, $27, $2a, $81, $84, $1e
	.byte $80, $27, $2e, $81, $84, $22, $81, $80, $2e, $81, $84, $1e, $81, $80, $2f, $81, $84, $20, $81, $80, $2e, $81, $84, $27
	.byte $80, $2c, $2a, $81, $2c, $81, $5c, $81, $23, $81, $25, $81, $84
	.byte $41, $0d
	.word @song0ref2908
	.byte $81, $84, $1e, $80, $28, $81, $5c
	.byte $41, $10
	.word @song0ref2933
	.byte $84, $1b, $80, $27, $2e, $81, $84, $25, $80, $2a, $2e, $81, $84, $22, $81, $20, $80, $2f, $5c, $81, $31, $81, $2e, $81
	.byte $2f, $81, $84, $1e, $80, $2c, $5c, $89, $42
	.word @song0ch12loop
@song0ch13:
@song0ch13loop:
@song0ref3043:
	.byte $7f, $92
@song0ref3045:
	.byte $14, $85, $14, $85, $5c, $85, $00, $e5, $14, $85, $14, $85, $5c, $85, $00, $a5, $76, $51, $02, $90, $8a, $38, $8d, $38
	.byte $8d, $38, $8d, $38, $8d
	.byte $41, $0f
	.word @song0ref3043
	.byte $e5
	.byte $41, $10
	.word @song0ref3045
	.byte $79, $8a, $34, $8d, $36, $8d, $38, $8d, $36, $8d, $7f, $92
@song0ref3093:
	.byte $14, $81, $5c, $81, $14, $81, $5c, $81, $17, $85, $5c, $81, $14, $81, $5c, $85, $14, $81, $5c, $81, $17, $85, $5c, $85
	.byte $13, $81, $5c, $81, $13, $81, $5c, $81, $17, $85, $5c, $81, $13, $81, $5c, $85, $13, $81, $5c, $81, $17, $85, $5c, $85
	.byte $12, $81, $5c, $81, $12, $81, $5c, $81, $17, $85, $5c, $81, $12, $81, $5c, $85, $12, $81, $5c, $81, $17, $81, $5c, $81
	.byte $12, $81, $5c, $81, $11, $81, $5c, $81, $11, $81, $5c, $81, $14, $85, $5c, $81, $0d, $85, $5c, $81, $0d, $81, $5c, $81
	.byte $14, $81, $0d, $81, $0f, $81, $10, $81, $10, $81, $5c, $81, $10, $81, $5c, $81, $14, $85, $5c, $81, $13, $85, $5c, $81
	.byte $13, $81, $5c, $81, $16, $81, $5c, $81, $0f, $81, $5c, $81, $14, $81, $5c, $81, $14, $81, $5c, $81, $17, $81, $14, $81
	.byte $5c, $81, $11, $89, $11, $81, $5c, $81, $14, $85, $0d, $85, $10, $81, $5c, $81, $10, $81, $5c, $81, $14, $81, $0f, $81
	.byte $5c, $81, $0d, $81, $5c, $85
@song0ref3267:
	.byte $0d, $81, $5c, $81, $14, $81, $5c, $81, $0d, $81, $5c, $81, $0f, $8d, $13, $8d, $16, $8d, $1b, $8d
	.byte $41, $ab
	.word @song0ref3093
	.byte $85, $5c, $81
	.byte $41, $0d
	.word @song0ref3267
	.byte $81, $5c, $81, $0f, $81, $5c, $85, $11, $81, $5c, $81, $13, $85, $0a, $81, $0f, $81, $11, $81, $13, $81, $16, $81, $1b
	.byte $81, $1f
@song0ref3322:
	.byte $81, $10, $8d, $12, $85, $5c, $81, $14, $8d, $5c, $85, $0f, $81, $14, $81, $1b, $81, $15, $9d, $14, $81, $08, $81, $0d
	.byte $81, $0f, $81, $14, $81, $19, $81, $1b, $81, $20
	.byte $41, $22
	.word @song0ref3322
	.byte $41, $22
	.word @song0ref3322
	.byte $81, $0d, $8d, $12, $89, $14, $8d, $5c, $85, $0f, $81, $14, $81, $1b, $81, $0d, $81, $5c, $89, $19, $81, $5c, $81, $0d
	.byte $81, $0d, $81, $5c, $8d, $19, $81, $5c, $89, $0d, $81, $5c, $89, $19, $81, $5c, $81, $0d, $81, $12, $81, $5c, $9d
@song0ref3409:
	.byte $0d, $81, $0d, $81, $0d, $81, $5c, $85, $0d, $81, $5c, $81, $12, $8d, $5c, $81, $10, $8d, $0f, $81, $0f, $81, $0f, $81
	.byte $5c, $85, $0f, $81, $5c, $81, $14, $8d, $5c, $81, $12, $8d
	.byte $41, $24
	.word @song0ref3409
	.byte $41, $24
	.word @song0ref3409
	.byte $41, $24
	.word @song0ref3409
	.byte $42
	.word @song0ch13loop
@song0ch14:
@song0ch14loop:
	.byte $88, $25, $89, $25, $85, $25, $85, $25, $85, $25, $85
@song0ref3469:
	.byte $25
@song0ref3470:
	.byte $91
@song0ref3471:
	.byte $25, $89, $25, $85, $25, $85, $25, $85, $25, $85, $25, $89, $25, $85, $25, $89, $25, $85, $25, $85, $25, $85, $25, $85
	.byte $25, $85, $7a, $25, $81, $7b, $25, $81, $7d, $25, $81, $7f
	.byte $41, $19
	.word @song0ref3471
	.byte $41, $1a
	.word @song0ref3470
	.byte $41, $1a
	.word @song0ref3470
	.byte $41, $1b
	.word @song0ref3470
@song0ref3519:
	.byte $25, $81, $7b, $25, $81, $25, $81, $7f, $25, $8d, $25, $8d, $25, $89
	.byte $41, $0d
	.word @song0ref3469
	.byte $41, $21
	.word @song0ref3470
	.byte $7f
	.byte $41, $19
	.word @song0ref3471
	.byte $41, $1b
	.word @song0ref3470
	.byte $41, $0c
	.word @song0ref3519
	.byte $41, $0d
	.word @song0ref3469
	.byte $41, $21
	.word @song0ref3470
	.byte $7f
	.byte $41, $19
	.word @song0ref3471
	.byte $41, $1b
	.word @song0ref3470
	.byte $41, $0c
	.word @song0ref3519
	.byte $25, $91
@song0ref3567:
	.byte $25, $99, $25, $85, $25, $85, $25, $89, $25, $85, $25, $9d, $25, $89, $25, $89, $25, $85
	.byte $41, $0d
	.word @song0ref3567
	.byte $9d
	.byte $41, $12
	.word @song0ref3567
	.byte $41, $0d
	.word @song0ref3567
	.byte $9d, $25, $9d, $25, $8d, $25, $8d
@song0ref3602:
	.byte $25, $81, $00, $81, $25, $81, $00, $85, $25, $81, $00, $81, $25, $81, $00, $89, $25, $81, $00, $85, $25, $81, $00, $81
	.byte $41, $18
	.word @song0ref3602
	.byte $41, $18
	.word @song0ref3602
	.byte $41, $18
	.word @song0ref3602
	.byte $41, $18
	.word @song0ref3602
	.byte $41, $18
	.word @song0ref3602
	.byte $41, $18
	.word @song0ref3602
	.byte $41, $0e
	.word @song0ref3602
	.byte $25, $81, $00, $99, $42
	.word @song0ch14loop
@song0ch15:
@song0ch15loop:
	.byte $8f, $88
@song0ref3657:
	.byte $25, $9d, $25, $9d, $25, $9d, $25, $8d, $8f, $25, $9d, $25, $9d, $25, $9d, $25, $8d, $8f
	.byte $41, $12
	.word @song0ref3657
	.byte $41, $0c
	.word @song0ref3657
	.byte $cd, $8f
	.byte $41, $12
	.word @song0ref3657
	.byte $41, $0c
	.word @song0ref3657
	.byte $cd, $8f
	.byte $41, $12
	.word @song0ref3657
	.byte $41, $0c
	.word @song0ref3657
	.byte $cd, $8f
	.byte $41, $0e
	.word @song0ref3657
	.byte $ad, $8f
	.byte $41, $0e
	.word @song0ref3657
	.byte $ad, $8f, $25, $ad, $00, $8d
	.byte $41, $12
	.word @song0ref3657
	.byte $41, $0e
	.word @song0ref3657
	.byte $ad, $42
	.word @song0ch15loop
@song0ch17:
@song0ch17loop:
	.byte $7a, $88
@song0ref3726:
	.byte $25, $00, $83
@song0ref3729:
	.byte $25, $00, $75, $25, $00, $7a, $25, $00, $83, $25, $00, $75, $25, $00, $7a, $25, $00, $83, $75, $25, $00, $25, $00, $7a
	.byte $25, $00, $75, $25, $00, $7a
	.byte $41, $0e
	.word @song0ref3729
@song0ref3762:
	.byte $25, $00, $75, $25, $00, $7a, $25, $00, $83, $25, $00, $75, $25, $00, $83, $7a, $25, $00, $75, $25, $00, $83, $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $19
	.word @song0ref3726
	.byte $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
@song0ref3927:
	.byte $7a, $25, $00, $83, $75, $25, $00, $83, $7a, $25, $00, $83, $75, $25, $00, $7a, $25, $00, $83, $25, $00, $75, $25, $00
	.byte $25, $00, $7a, $25, $00, $83, $75, $25, $00, $83, $7a
	.byte $41, $0c
	.word @song0ref3726
@song0ref3965:
	.byte $25, $00, $83, $25, $00, $75, $25, $00, $25, $00, $7a, $25, $00, $75, $25, $00, $7a, $25, $00, $75, $25, $00
	.byte $41, $1a
	.word @song0ref3927
	.byte $7a
	.byte $41, $0c
	.word @song0ref3726
	.byte $41, $11
	.word @song0ref3965
	.byte $41, $1a
	.word @song0ref3927
	.byte $7a
	.byte $41, $0c
	.word @song0ref3726
	.byte $41, $11
	.word @song0ref3965
	.byte $41, $1a
	.word @song0ref3927
	.byte $7a, $25, $00, $8b, $75, $25, $00, $8b, $7a, $25, $00, $8b, $75, $25, $00, $8b, $7a, $25, $00, $8b, $75, $25, $00, $87
	.byte $7a
	.byte $41, $11
	.word @song0ref3965
	.byte $7a
	.byte $41, $11
	.word @song0ref3726
	.byte $25, $00, $75, $25, $00, $7a, $25, $00, $75, $25, $00, $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $11
	.word @song0ref3726
	.byte $25, $00, $75, $25, $00, $7a, $25, $00, $75, $25, $00, $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $11
	.word @song0ref3726
	.byte $25, $00, $75, $25, $00, $7a, $25, $00, $75, $25, $00, $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $7a
	.byte $41, $11
	.word @song0ref3726
	.byte $25, $00, $75, $25, $00, $7a, $25, $00, $75, $25, $00, $7a
	.byte $41, $0e
	.word @song0ref3729
	.byte $41, $11
	.word @song0ref3762
	.byte $42
	.word @song0ch17loop
@song0ch18:
@song0ch18loop:
	.byte $ff, $ff, $ff, $ff, $ff, $f3, $88, $25, $81, $25, $81, $25, $81, $00, $fd, $ff, $ff, $f3, $25, $81, $25, $81, $25, $81
	.byte $00, $fd, $ff, $ff, $f3, $25, $81, $25, $81, $25, $81, $00, $fd
@song0ref4167:
	.byte $e3, $25, $81, $00, $81, $25, $81, $25, $81, $00, $81, $25, $81, $00, $81, $ff
	.byte $41, $0f
	.word @song0ref4167
	.byte $bf, $ff, $ff, $ff, $eb, $25, $81, $00, $81, $25, $81, $25, $81, $25, $81, $42
	.word @song0ch18loop
@song0ch19:
@song0ch19loop:
	.byte $41, $0e
	.word @song0ref4
	.byte $ff, $ff, $ff, $ff, $ab, $88, $25, $81, $00, $81, $25, $81, $25, $81, $25, $81, $00, $fd, $ff, $ff, $ff, $42
	.word @song0ch19loop
@song1ch0:
	.byte $46, $0a
@song1ch0loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song1ch0loop
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch13:
@song1ch12:
@song1ch11:
@song1ch10:
@song1ch9:
@song1ch8:
@song1ch7:
@song1ch6:
@song1ch5:
@song1ch3:
@song1ch2:
@song1ch1:
@song1ch1loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song1ch1loop
@song1ch4:
@song1ch4loop:
	.byte $22, $23, $24, $25, $17, $18, $19, $1a, $1b, $11, $12, $13, $14, $15, $00, $99, $1c, $00, $83, $0b, $0c, $21, $05, $03
	.byte $06, $02, $04, $07, $16, $01, $0d, $09, $00, $83, $20, $00, $83, $10, $0f, $0a, $0e, $08, $00, $83, $1f, $1d, $00, $81
	.byte $1e, $00, $ff, $ff, $fb, $42
	.word @song1ch4loop
@song2ch0:
	.byte $46, $06, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $97, $79, $4f, $01, $80, $1b, $81, $1c, $81, $4f, $00, $1e, $83, $00
	.byte $4f, $02, $1c, $83, $00, $4f, $00, $1b, $81, $4f, $02, $20, $4f, $01, $83, $00, $1e, $4f, $00, $81, $81, $00, $20, $81
	.byte $4f, $02, $81, $00, $8b, $4f, $01, $1b, $81, $1c, $81, $4f, $00, $1e, $83, $00, $4f, $02, $1c, $83, $00, $4f, $00, $1b
	.byte $81, $4f, $01, $19, $4f, $02, $83, $00, $19, $4f, $00, $81, $17, $81, $4f, $02, $81, $00, $83, $75, $4f, $00, $19, $81
	.byte $17, $81, $00, $81, $79, $4f, $01, $1b, $81, $1c, $81, $4f, $00, $1e, $83, $00, $4f, $02, $1c, $83, $00, $4f, $00, $1b
	.byte $81, $4f, $02, $20, $4f, $01, $83, $00, $1e, $4f, $00, $81, $81, $00, $20, $81, $4f, $01, $81, $00, $87, $4f, $02, $1b
	.byte $00, $4f, $01, $1b, $81, $4f, $00, $1c, $81, $4f, $00, $1e, $83, $00, $4f, $02, $1c, $83, $00, $4f, $00, $1b, $81, $4f
	.byte $01, $19, $4f, $02, $83, $00, $19, $4f, $00, $81, $17, $83, $00, $83, $75, $1b, $81, $17, $81, $7b, $1b, $81, $17, $81
	.byte $1b, $81
@song2ref195:
	.byte $00, $9d
@song2ref197:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $44, $00
@song2ch1:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $97, $76, $4f, $01, $80, $17, $81, $17, $81, $1b, $83, $00, $19, $83, $00, $17
	.byte $81, $1b, $83, $00, $1b, $81, $81, $00, $1b, $83, $00, $8b, $17, $81, $17, $81, $1b, $83, $00, $19, $83, $00, $17, $81
	.byte $16, $83, $00, $16, $81, $14, $83, $00, $8f, $17, $81, $17, $81, $1b, $83, $00, $19, $83, $00, $17, $81, $1b, $83, $00
	.byte $1b, $81, $81, $00, $1b, $83, $00, $87, $17, $00, $17, $81, $17, $81, $1b, $83, $00, $19, $83, $00, $17, $81, $16, $83
	.byte $00, $16, $81, $14, $83, $00, $97
	.byte $41, $2e
	.word @song2ref197
	.byte $9f, $44, $00
@song2ch19:
@song2ch18:
@song2ch16:
@song2ch13:
@song2ch12:
@song2ch7:
@song2ch2:
	.byte $41, $2e
	.word @song2ref197
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $44, $00
@song2ch3:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $8f, $71, $51, $03, $a0, $80, $40, $0c, $8b, $81, $51, $fe, $00, $40, $0b, $9b
	.byte $7a, $00
	.byte $41, $2e
	.word @song2ref197
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $44, $00
@song2ch4:
	.byte $9f, $9f, $9f, $9b, $20, $81, $87
@song2ref433:
	.byte $02, $81, $05, $05, $81, $03, $04, $06, $02, $81, $05, $81, $05, $03, $81, $06, $02, $81, $05, $05, $81, $03, $04, $06
	.byte $02, $05, $02, $05, $05, $03, $81, $06
	.byte $41, $1c
	.word @song2ref433
	.byte $00, $9d, $05, $03, $81, $06
	.byte $41, $20
	.word @song2ref433
	.byte $41, $20
	.word @song2ref433
	.byte $41, $20
	.word @song2ref433
	.byte $41, $1c
	.word @song2ref433
	.byte $41, $31
	.word @song2ref195
@song2ch5:
	.byte $7d, $8c
@song2ref492:
	.byte $2c, $87, $2f, $81, $2e, $8f, $2e, $87, $31, $81, $2f, $83, $7a, $2c, $2e, $2c, $2e, $2c, $2e, $7d, $2c, $87, $2f, $81
	.byte $2e, $87, $36, $81, $31, $81, $9f
	.byte $41, $1c
	.word @song2ref492
	.byte $87, $36, $81, $2f, $91, $00, $9d
	.byte $41, $1c
	.word @song2ref492
	.byte $87, $36, $81, $2f, $91
	.byte $41, $1c
	.word @song2ref492
	.byte $87, $36, $81, $2f, $91
	.byte $41, $31
	.word @song2ref195
@song2ch6:
	.byte $00, $77, $8c
@song2ref556:
	.byte $2c, $87, $2f, $81, $2e, $8d, $81, $2e, $87, $31, $81, $2f, $83, $75, $2c, $2e, $2c, $2e, $2c, $2e, $77, $2c, $87, $2f
	.byte $81, $2e, $87, $36, $81, $31, $9f, $00
	.byte $41, $1c
	.word @song2ref556
	.byte $89, $36, $81, $2f, $8f, $00, $9d, $00
	.byte $41, $1c
	.word @song2ref556
	.byte $89, $36, $81, $2f, $8f, $00
	.byte $41, $1c
	.word @song2ref556
	.byte $89, $36, $81, $2f, $8f
	.byte $41, $31
	.word @song2ref195
@song2ch8:
	.byte $78, $90
@song2ref622:
	.byte $25, $28, $25, $2f, $74, $81, $78, $81, $74, $81, $78, $25, $74, $00, $78, $2e, $74, $81, $77, $81, $73, $81, $74, $81
	.byte $71, $83, $78, $27, $2a, $27, $2e, $74, $81, $78, $81, $74, $81, $78, $2f, $74, $00, $78, $2e, $2c, $2a, $2c, $27, $25
	.byte $23, $25, $28, $25, $2f, $74, $81, $78, $81, $74, $81, $78, $25, $74, $00, $78, $2e, $74, $81, $77, $81, $73, $81, $74
	.byte $81, $71, $83, $78, $27, $2a, $27, $2e, $74, $81, $78, $81, $2f, $2c, $74, $81, $77, $81, $73, $81, $75, $81, $71, $81
	.byte $73, $81, $71, $81, $81, $78
	.byte $41, $3e
	.word @song2ref622
	.byte $00, $9d, $78
	.byte $41, $3e
	.word @song2ref622
	.byte $78
	.byte $41, $3e
	.word @song2ref622
	.byte $41, $31
	.word @song2ref195
@song2ch9:
	.byte $7b, $94
@song2ref743:
	.byte $25, $5c, $25, $5c, $2c, $5c, $81, $2a, $5c, $81, $2a, $5c, $31, $5c, $83, $27, $5c, $27, $5c, $2e, $5c, $81, $2c, $5c
	.byte $8d
	.byte $41, $18
	.word @song2ref743
	.byte $1b, $20, $22, $23, $25, $27, $2a
	.byte $41, $19
	.word @song2ref743
	.byte $41, $19
	.word @song2ref743
	.byte $41, $30
	.word @song2ref195
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $44, $00
@song2ch10:
	.byte $9f, $91, $77, $51, $02, $b0, $82, $3d, $3b, $3d, $3b, $3d, $3b, $3d, $3b, $85, $38, $81, $33, $36, $81, $38, $83, $40
	.byte $4e, $81, $3d, $81, $3d, $85, $3a, $81, $36, $38, $85, $00, $87
@song2ref836:
	.byte $3b, $85, $38, $81, $33, $36, $81, $38, $83, $40, $4e, $81, $3d, $81, $3d, $85, $3a, $81, $36, $38, $81, $77, $51, $02
	.byte $b0, $3d, $3b, $3d, $3b, $3d, $3b, $3d, $3b, $85, $38, $81, $33, $36, $81, $38, $83, $40, $4e, $81, $3d, $81, $83, $00
	.byte $81, $40, $4e, $81, $3b, $91, $00, $9d
	.byte $41, $2f
	.word @song2ref836
	.byte $41, $31
	.word @song2ref836
	.byte $41, $2f
	.word @song2ref197
@song2ch11:
	.byte $7d, $90
@song2ref904:
	.byte $31, $34, $31, $3b, $77, $81, $7d, $81, $77, $81, $7d, $31, $77, $81, $7d, $3a, $77, $81, $7a, $81, $74, $81, $77, $81
	.byte $72, $83, $7d, $33, $36, $33, $3a, $77, $81, $7d, $81, $77, $81, $7d, $3b, $77, $81, $7d, $3a, $38, $36, $38, $33, $31
	.byte $2f, $31, $34, $31, $3b, $77, $81, $7d, $81, $77, $81, $7d, $31, $77, $81, $7d, $3a, $77, $81, $7a, $81, $74, $81, $77
	.byte $81, $72, $83, $7d, $33, $36, $33, $3a, $77, $81, $7d, $81, $3b, $38, $77, $81, $7a, $81, $74, $81, $78, $81, $74, $81
	.byte $75, $81, $72, $81, $74, $81, $7d
	.byte $41, $3e
	.word @song2ref904
	.byte $00, $9d, $7d
	.byte $41, $3e
	.word @song2ref904
	.byte $7d
	.byte $41, $3e
	.word @song2ref904
	.byte $41, $31
	.word @song2ref195
@song2ch14:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $93, $88, $40, $01, $00, $87
@song2ref1038:
	.byte $40, $01, $00, $83, $40, $01, $00, $83, $40, $01, $00, $83, $40, $01, $00, $83, $40, $01, $00, $83, $40, $01, $00, $83
	.byte $40, $01, $00, $83, $40, $01, $00, $83
	.byte $41, $18
	.word @song2ref1038
	.byte $41, $18
	.word @song2ref1038
	.byte $41, $18
	.word @song2ref1038
	.byte $41, $2e
	.word @song2ref197
	.byte $9f, $44, $00
@song2ch15:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $87, $88
@song2ref1097:
	.byte $40, $01, $00, $8b, $40, $01, $00, $83, $87, $40, $01, $00, $8b, $40, $01, $00, $83, $87, $40, $01, $00, $8b, $40, $01
	.byte $00, $83, $87, $40, $01, $00, $8b, $40, $01, $00, $83, $87
	.byte $41, $1b
	.word @song2ref1097
	.byte $41, $2e
	.word @song2ref197
	.byte $9f, $44, $00
@song2ch17:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $7b, $88, $40, $01, $00, $40, $01, $40, $01, $40, $01, $00, $40, $01, $40, $01
	.byte $40, $01, $00, $83, $40, $01, $40, $01
@song2ref1175:
	.byte $40, $01, $40, $01, $40, $01, $00, $40, $01, $40, $01, $40, $01, $00, $40, $01, $40, $01, $40, $01, $00, $40, $01, $40
	.byte $01, $40, $01, $00, $40, $01, $40, $01, $40, $01, $00, $40, $01, $40, $01, $40, $01, $00
	.byte $41, $18
	.word @song2ref1175
	.byte $41, $18
	.word @song2ref1175
	.byte $41, $18
	.word @song2ref1175
	.byte $41, $18
	.word @song2ref1175
	.byte $40, $01, $40, $01, $40, $01, $00, $40, $01, $40, $01, $40, $01, $00, $40, $01, $40, $01
	.byte $41, $31
	.word @song2ref195
